<?php

/**
 * @file
 * Enables Honeypot check on registration form submit.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function user_regiastration_honeypot_form_user_register_form_alter(&$form, &$form_state) {
  $form['field_country']=array(
    '#type'=>'textfield',
    '#attributes'=>array(
      'class'=>array('required')
    )
  );
  array_push($form['#validate'],'user_regiastration_honeypot_validate');
}


/**
 * Honeypot validate.
 */
function user_regiastration_honeypot_validate(&$form, &$form_state) {
  if(!form_get_errors() && isset($form_state['values']['field_country']) && trim($form_state['values']['field_country']) != ''){
    $form['#submit'] = array('user_regiastration_honeypot_fakesubmit');
  }
}


function user_regiastration_honeypot_fakesubmit(&$form, &$form_state){
  drupal_set_message(t('A welcome message with further instructions has been sent to your e-mail address.<br/>If you do not receive an email within the next 5 minutes, please check your SPAM folder.'));
}